
name: FB Video Post

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Video Script
      run: python main.py
